# Default values for knative-serving.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

route:
  domains: []
  # - domain: example.com
  # - domain: example.org
  #   selector:
  #     app: nonprofit
  # - domain: svc.cluster.local
  #   selector:
  #     app: secret

  # domainTemplate specifies the golang text template string to use
  # when constructing the Knative service's DNS name. The default
  # value is "{{.Name}}.{{.Namespace}}.{{.Domain}}". And those three
  # values (Name, Namespace, Domain) are the only variables defined.
  #
  # Changing this value might be necessary when the extra levels in
  # the domain name generated is problematic for wildcard certificates
  # that only support a single level of domain name added to the
  # certificate's domain. In those cases you might consider using a value
  # of "{{.Name}}-{{.Namespace}}.{{.Domain}}", or removing the Namespace
  # entirely from the template. When choosing a new value be thoughtful
  # of the potential for conflicts - for example, when users choose to use
  # characters such as `-` in their service, or namespace, names.
  # {{.Annotations}} can be used for any customization in the go template if needed.
  # We strongly recommend keeping namespace part of the template to avoid domain name clashes
  # Example '{{.Name}}-{{.Namespace}}.{{ index .Annotations "sub"}}.{{.Domain}}'
  # and you have an annotation {"sub":"foo"}, then the generated template would be {Name}-{Namespace}.foo.{Domain}
  domainTemplate: "{{.Name}}.{{.Namespace}}.{{.Domain}}"

  # tagTemplate specifies the golang text template string to use
  # when constructing the DNS name for "tags" within the traffic blocks
  # of Routes and Configuration.  This is used in conjunction with the
  # domainTemplate above to determine the full URL for the tag.
  tagTemplate: "{{.Name}}-{{.Tag}}"
