apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: sleepingservice
  namespace: default
spec:
  template:
    metadata:
      annotations:
        # Default: Knative concurrency-based autoscaling with
        # 100 requests in-flight per pod.
        autoscaling.knative.dev/class:  kpa.autoscaling.knative.dev
        autoscaling.knative.dev/metric: concurrency
        # Changed target to 1 to showcase autoscaling
        autoscaling.knative.dev/target: "1"

        # Alternative: Kubernetes CPU-based autoscaling.
        # autoscaling.knative.dev/class:  hpa.autoscaling.knative.dev
        # autoscaling.knative.dev/metric: cpu

        # Disable scale to zero with a minScale of 1.
        autoscaling.knative.dev/minScale: "1"
        # Limit max scaling to 5 pods.
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        # Replace {username} with your actual DockerHub
        - image: docker.io/randax/sleepingservice:v1