# Default values for istio-gke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

istio:
  version: 1.3.1
  mtls: false

  autoInjectionNamespaces:
    - default

  sidecarInjector:
    enabled: true

    rewriteAppHTTPProbe: false
    autoInjectionPolicyEnabled: true

    initCNIConfiguration:
      enabled: true

  gateways:
    enabled: true
    ingress:
      enabled: true
      serviceType: "LoadBalancer"
      loadBalancerIP: ""
