# Default values for istio-gke.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

istio:
  version: 1.2.4
  mtls: false

  autoInjectionNamespaces:
    - default

  sidecarInjector:
    enabled: true

    initCNIConfiguration:
      enabled: true
